### DISCUSSION TITLE
Cache ignores files in `.gitignore`

### DISCUSSION THREAD

**Discussion by j0hannr** [actions/toolkit#1936] [Q&A]
Files that are on the `.gitignore` list are cached but not restored.

### Example
In the following example dependencies are created but not stored.

```yml
name: Cache Example

on:
  workflow_dispatch:

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - name: Create Test File
        run: echo "generated" > hello.txt
      
      - name: Cache Dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            .
            hello.txt
          key: ${{ runner.os }}-project-${{ hashFiles('package-lock.json') }}
      
      - name: List Cache Contents
        run: |
          echo "--- Root Directory ---"
          ls -la
          echo "--- Content of hello.txt ---"
          cat hello.txt

  restore-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .
            hello.txt
          key: ${{ runner.os }}-project-${{ hashFiles('package-lock.json') }}
      
      - name: List Restored Cache Contents
        run: |
          echo "--- Root Directory ---"
          ls -la
          echo "--- Content of hello.txt ---"
          cat hello.txt # files does not exist
```

## Demo
I created a [demo](https://github.com/viadkt/action-test/actions/runs/12870328416) workflow to visulise the behaviour.

Is this behaviour expected?
Can this bahaviour changed to cache and restore files on the git ignore list?
