### ISSUE TITLE
toJson in pull request triggered by Dependabot fails

### ISSUE THREAD

**Issue by guwirth** [actions/toolkit#1016]
Hi,

Starting last week action fails with a simple:

https://github.com/SonarOpenCommunity/sonar-cxx/runs/5515963736
```
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'
```

This happens with **Dependabot**. Think it’s because their commit message contains some html code?

Regards,

**Comment by henrygriffiths** [comment]
@guwirth I tried to view the logs for that action run, but they have expired. I believe this is an issue with the bash shell and how it interprets quoting. Here is the step that I have in one of my workflows that works with every input that has been thrown at it so far (including inputs with html tags):

```yaml
    - name: Dump GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
```
