### ISSUE TITLE
Support hashing files outside the workspace directory

### ISSUE THREAD

**Issue by PeterJCLaw** [actions/toolkit#1035]
Currently [`hashFiles` ignores files outside the workspace](https://github.com/actions/toolkit/blob/main/packages/glob/src/internal-hash-files.ts#L16-L19). This means that it cannot be used to hash files which appear within an Action. In turn this means that packages such as `actions/setup-python` cannot be used with files from the Action (see for example https://github.com/actions/setup-python/issues/361), making them hard to use within composite Actions.

It would be great if `hashFiles` could support these files as it would enable more powerful composite Actions.

**Comment by fjelliott** [comment]
I also would like to see this issue resolved. I am also having issues with caching with actions/setup-python#361 in a composite action. The maintainer of that action says that this bug can't be fixed until the issue in this repository is resolved.

**Comment by flobernd** [comment]
Same scenario for me: `actions/setup-python` inside a composite action.

As a workaround I have to copy the scripts to the workspace directory. Not a super nice solution tho (there might already be a directory with the same name and so on..):

```yaml
- name: Set up Scripts
  id: setup-scripts
  shell: bash
  run: |
    SCRIPTS_PATH="$GITHUB_WORKSPACE/scripts"
    cp -r "${{ github.action_path }}/../../scripts" "$SCRIPTS_PATH"
    echo "SCRIPTS_PATH=$SCRIPTS_PATH" >> $GITHUB_ENV
    echo "::set-output name=scripts-path::$(echo $SCRIPTS_PATH)"
````
