### ISSUE TITLE
Add a event to trigger a workflow if a Template Repository is instantiated

### ISSUE THREAD

**Issue by gprossliner** [actions/toolkit#1054]
**Describe the enhancement**

Provide a new event like these https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows that is triggered if a Repository is created from a Template Repository.

This would allow a Template author to automate initialization of a Repository. The workflow should run in the newly create Repository, not in the Template Repository.

**Example when this would be useful**

* I have a Template named "standard-nuget-package". Within this repository, there are files and folders named like "standard-nuget-package.csproj". This Template includes a workflow triggered on instantiation (maybe `template_instantiated`), that renames files, folders and replaces file contents to replace "standard-nuget-package" with the name of the newly created Repository, and commits the changes.
* Another user creates a new Repository named "MyCoolPackage"
* The workflow triggers and performs rename / replace operations, and commits these changes
* The new Repository is ready to go

I can image more of such initialization workflows that would benefit from this event.

**Comment by jlumbroso** [comment]
I think this would be a really big deal—it would supercharge GitHub's "template repository" concept, and use GitHub Actions to make it easier for people to "consume" a template repository, lowering the friction to use them.

**Comment by sjmiller609** [comment]
I used a workflow like this in my use case.

```
# this file should only be editted from (insert your template repo name here)
name: Cookiecutter format

on:
  # I have found this event triggers on initial creation of new repository
  push:
    branches:
      - '**'

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # This is my application specific use case,
      # I am formatting the code here using Cookiecutter
      # In the reader's case, they should modify the code however they want to do it.
      - name: Cookiecutter format
        uses: ./.github/actions/self-initialize-cookiecutter
        with:
          repo_name: ${{ github.event.repository.name }}
      - name: Create Pull Request
        # My repository that is a template repository includes the string "cookiecutter"
        if: ${{ ! contains(github.event.repository.name, 'cookiecutter') }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Cookiecutter format with repo_name as ${{ github.event.repository.name }}"
          title: Cookiecutter format
          body: |
            # Cookiecutter format PR
            Cookiecutter format with repo_name as ${{ github.event.repository.name }}
          branch: cookiecutter-format
          ```

**Comment by gprossliner** [comment]
@sjmiller609 this looks quite interesting! Thank you

**Comment by svenvanderburg** [comment]
@sjmiller609 this github action will be triggered on pushes from **all** branches right? I would be interested in triggering a github action **only** upon repository instantiation.

**Comment by jlumbroso** [comment]
@svenvanderburg Look here for an example of what you are trying to do (I think):

https://github.com/jlumbroso/hugo-theme-bootstrap-skeleton

**Comment by svenvanderburg** [comment]
@jlumbroso this is the same solution as @sjmiller609 proposed right? By specifying:
```
on:
  push:
    branches:
      - '**'
```
I tested this, and it does trigger on initialization. But it also triggers on all following commits... This last behavior is not what I want.

**Comment by svenvanderburg** [comment]
[Here](https://stackoverflow.com/questions/71872019/ensure-that-a-workflow-in-github-actions-is-only-ever-triggered-once) is a workaround. Basically, you disable the workflow after it has run.

A fully working, but untested solution would be:

```
name: Execute workflow only upon repository initialisation

on:
  push:
    branches:
      - '**'
 
jobs:
    - name: Disable this workflow
      shell: bash
      run: |
        gh workflow disable -R $GITHUB_REPOSITORY "${{ github.workflow }}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by kishaningithub** [comment]
I stumbled upon the following github action that setup everything once the template is cloned
https://github.com/laucia/cookiecutter-pypackage/blob/main/.github/workflows/template_baking.yaml

**Comment by nizarmah** [comment]
> This would allow a Template author to automate initialization of a Repository. **The workflow should run in the newly create Repository, not in the Template Repository.**

The following's my approach to triggering a workflow if a repository is created using my template repository.
The workflow runs upon branch/tag creation as well, but it gets canceled because of the conditional expression.

I've already tested it a lot with a scrapped project. Hope it helps! 

```yml
name: Setup repository

on:
  create

jobs:
  create_issue:
    if: github.event.ref == github.event.master_branch
    name: Create issue

    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:

      - uses: imjohnbo/issue-bot@v3
        with:
          title: "Test issue"
```
