### ISSUE TITLE
Re-run checks not working when there is a filter 

### ISSUE THREAD

**Issue by ibakshay** [actions/toolkit#109]
Hello,
One of the `steps`  in the `Job` didn't  pass and so the github action check   has failed. 
![Screen Shot 2019-09-04 at 16 37 29](https://user-images.githubusercontent.com/33329946/64265383-17bc2a00-cf33-11e9-8b00-eaac5f675db1.png)

Then I triggered the `Re-run checks` without changing anything. The build has skipped the `step` which was failed and the check  has passed. Ideally It should **fail again**.  This is not the first time, I have checked multiple times with different workflows. 

**After Triggering Re_run checks**

![Screen Shot 2019-09-04 at 16 39 30](https://user-images.githubusercontent.com/33329946/64265417-2571af80-cf33-11e9-88bd-dae6104706b6.png)

Please ask me if something is not clear.

**Comment by ibakshay** [comment]
Could you please tell Whether It is a bug or I am missing something ? 😅.
Now after triggering Re_run checks, check status  is `pending` forever. 
https://github.com/ibakshay/test-action-workflow/actions
![Screen Shot 2019-09-09 at 16 45 42](https://user-images.githubusercontent.com/33329946/64541015-71509a00-d321-11e9-9603-b141afa65c04.png)

**Comment by ibakshay** [comment]
I debugged and found out that the `re-run checks` is not working when there is a filter something like 
```yml
    - name: "TEST ACTION"
      if: github.event.action == 'opened' || github.event.action == 'edited'
      uses: ibakshay/action-template@dev
      with: 
        mytoken: ${{ secrets.GITHUB_TOKEN }}
```

If the remove the filter ` if: github.event.action == 'opened' || github.event.action == 'edited'` for that  step, then `re-run checks` is working fine. 

I have checked for both `pull_request` and the `issues` event. The same issue is there when there is a filter for both the events.
