### ISSUE TITLE
Cannot access matrix inside `if`

### ISSUE THREAD

**Issue by ddaaac** [actions/toolkit#1111]
**Describe the bug**
Cannot access matrix inside `if` in jobs.

**To Reproduce**

```
# workflow.yml

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['admin', 'server']
    if: ${{ contains('admin', matrix.module) }}

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

```
When I run this action, i got an error like below.
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/43440195/172304162-55781d42-cb72-47d9-bd9e-eb9b9ea8ceb9.png">

**Expected behavior**
I can access to 'matrix' in `if`. In [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context),
> You can access this context from any job or step in a workflow.
