### ISSUE TITLE
core: `getMultilineInput` not trimming whitespace

### ISSUE THREAD

**Issue by bicstone** [actions/toolkit#1186]
**Describe the bug**
core.getInput is [trimming whitespace](https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L17) by default, but core.getMultilineInput is not.
Also, core.getMultilineInput ignores trimWhitespace option.

**To Reproduce**

action.yml

```yml
# ...
inputs:
  option:
    description: a multiline option
```

index.js

```js
import * as core from "@actions/core"

const option = core.getMultilineInput("option", {
  trimWhitespace: true,
})

core.info(option)
```

workflow.yml

```yml
# ...
jobs:
  test:
    # ...
    steps:
      - uses: # ...
        with:
          option: |-
             a
             b 
             c 
```

-> `["a ", " b ", " c"]`

**Expected behavior**
-> `["a", "b", "c"]`
