### ISSUE TITLE
github.context.payload.pull_request.title always remains the same when rerunning action.

### ISSUE THREAD

**Issue by mvashishtha** [actions/toolkit#1204]
**Describe the bug**

I am using a github action triggered by pull requests that is basically doing:

```python
const github = require('@actions/github');
const pullRequestTitle = github.context.payload.pull_request.title;
```

The full code is [here](https://github.com/Slashgear/action-check-pr-title/blob/692277b1d7de95263491baa9a0f1ae78d4016b97/src/run.js).

When I update the PR title after the action runs once, then rerun the action, the action reuses the old PR title! The result is that the action that is supposed to check my PR title can only be used once per commit. I have to push an empty commit to get the action to use the new PR title.

Sample runs: https://github.com/modin-project/modin/actions/runs/3231387461/jobs/5291018196

**To Reproduce**
1. Add this to `.github/workflows/ci-required.yml` in some github project:
```
name: ci-required
on: pull_request
jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: Slashgear/action-check-pr-title@v3.0.0
      with:
        regexp: '^(?:FEAT|DOCS|FIX|REFACTOR|TEST|PERF)-#\d+:'
```
1. Make a PR with valid title, e.g. TEST-#4982: Require format for PR descriptions instead of commit descriptions
2. See the check-pr-title job pass, e.g. [here](https://github.com/modin-project/modin/actions/runs/3231387461/attempts/1)
3. change PR title so it's invalid, e.g. "TESTz-#4982: Require format for PR descriptions instead of commit descriptions"
4. rerun check-pr-title job in github UI
5. see check-pr-title job pass even though PR title is now invalid
6. push empty commit to branch
7. see check-pr-title job fail because it uses updated PR title

**Expected behavior**
After I update PR title and re-run Github Action, action should use updated PR title.
