### ISSUE TITLE
### What would you like to be added?

### ISSUE THREAD

**Issue by Boobs1** [actions/toolkit#1221]
### What would you like to be added?

An option that allows you to download a specific file from an artifact.

So f.e. defining a workflow step like
```yaml
- uses: actions/download-artifact@v3
  with:
    name: some-artifact
    file: some-file.txt
```
would download `some-file.txt` from the artifact `some-artifact`

### Why is this needed?

There are cases where you want to save multiple files into a single artifact to not have to make multiple steps uploading each one individually for later usage in a different job.
The issue is, that the action, as of right now, is just downloading the artifact as a whole, meaning it also loads files that may not be needed by the specific step in the end, as it's basically bloat that will be discarded at the end.

As an example, assuming we want to use a Matrix setup to deal with each individual file (i.e. upload them to different platforms), while creating said files should only be done once by having it as a separate job, creating multiple files like this
```yaml
jobs:
  createFiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p path/to/artifact
    - run: echo Platform 1 > path/to/artifact/platform_1.txt
    - run: echo Platform 1 > path/to/artifact/platform_2.txt
    - run: echo Platform 1 > path/to/artifact/platform_3.txt
    - run: echo Platform 1 > path/to/artifact/platform_4.txt
```
would require one of multiple solutions:

1. Multiple artefacts:
   ```yaml
   jobs:
     createFiles:
       runs-on: ubuntu-latest
       steps:
       # Creating files
       - uses: actions/upload-artifact@v3
         with:
           name: my-artifact-1
           path: path/to/artifact/platform_1.txt
       - uses: actions/upload-artifact@v3
         with:
           name: my-artifact-2
           path: path/to/artifact/platform_2.txt
       - uses: actions/upload-artifact@v3
         with:
           name: my-artifact-3
           path: path/to/artifact/platform_3.txt
       - uses: actions/upload-artifact@v3
         with:
           name: my-artifact-4
           path: path/to/artifact/platform_4.txt
     publishFiles:
       runs-on: ubuntu-latest
       strategy:
         matrix:
           include:
           - platform: 1
           - platform: 2
           - platform: 3
           - platform: 4
       steps:
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
           name: my-artifact-${{ matrix.platform }}
       - uses: example/example-publish@v1 # Mockup action
         with:
           # Assuming the action supports Glob patterns, 'platform_?.txt' can be used to simplify things
           file: platform_?.txt
   ```
   Downside is that it obviously has multiple steps to create multiple artefacts which isn't optimal, but would allow a relatively simple handling of the file in follow-up steps.

2. One artifact:
   ```yaml
   jobs:
     createFiles:
       runs-on: ubuntu-latest
       steps:
       # Creating files
       - uses: actions/upload-artifact@v3
         with:
           name: my-artifact
           path: path/to/artifact/platform_?.txt
     publishFiles:
       runs-on: ubuntu-latest
       strategy:
         matrix:
           include:
           - platform: 1
           - platform: 2
           - platform: 3
           - platform: 4
       steps:
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
           name: my-artifact
       - uses: example/example-publish@v1 # Mockup action
         with:
           # Assuming the action supports Glob patterns, this won't work with 'platform_?.txt'
           file: platform_${{ matrix.platform }}.txt
   ```
   A downside here is, that the entire artefact is downloaded. For TXT files may this not be that big of a deal, but depending on what is uploaded as an artefact can this cause several MBs of data to be downloaded in the end for just one to actually be used.

3. The idea:
   ```yaml
   jobs:
     createFiles:
       runs-on: ubuntu-latest
       steps:
       # Creating files
       - uses: actions/upload-artifact@v3
         with:
           name: my-artifact
           path: path/to/artifact/platform_?.txt
     publishFiles:
       runs-on: ubuntu-latest
       strategy:
         matrix:
           include:
           - platform: 1
           - platform: 2
           - platform: 3
           - platform: 4
       steps:
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
           name: my-artifact
           file: platform_${{ matrix.platform }}.txt
       - uses: example/example-publish@v1 # Mockup action
         with:
           # Thanks to the above option, glob patterns can be used here again.
           file: platform_?.txt
   ```

I'm not sure if the example I gave really shows the benefits. I'm sure there are other, more complex examples that would justify such an option to be present.
Of course, this also depends on if the way download-artifact works are making a targeted download of specific files possible.

In the end, the main benefit would be to keep files in one artefact without having to download not needed ones from an artifact, only to discard them at the end.

__Originally posted by @Andre601 in https://github.com/actions/download-artifact/issues/176__
