### ISSUE TITLE
Unable to echo specific output from `core.setOutput()` in subsequent steps

### ISSUE THREAD

**Issue by martijnvanschie** [actions/toolkit#1261]
Writing the custom action using the [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action) i am unable to echo the output value in a next step when using the output name. Using a `.*` function does print all the values.

I am familiar with the chances to the way output is [changing](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and am using the latest version of `actions/core`.

```json
{
  "dependencies": {
    "@actions/core": "^1.10.0",
    "@actions/github": "^5.1.1"
  }
}
```

Below is the part in the javascript that sets the output. 

Do note the different ways of using quotes because I'm testing this.

```javascript
  core.startGroup('Setting action outputs.');
    core.info('Setting version-assembly');
    core.setOutput('version-assembly', `${assemblyVersion}`);

    core.info('Setting version-file');
    core.setOutput("version-file", fileVersion);

    core.info('Setting version-informational');
    core.setOutput("version-informational", informationalVersion);

    core.info('Setting version-package');
    core.setOutput("version-package", packageVersion);

    core.info('Setting buildnumber');
    core.setOutput("buildnumber", buildnumber);
  core.endGroup();
  ```
  
  Using the following steps to set and print the output
  
  ```yaml
  - name: Create version step
	id: dotnetversion
	uses: ./
	with:
	  baseversion: 'v1.2.3-beta.4'

  - name: Print all output joined
	run: echo all outputs ${{join(steps.dotnetversion.outputs.*, '\n')}}
	shell: bash   

  - name: Print version-assembly
	run: echo version-assembly ${{ steps.dotnetversions.outputs.version-assembly }}
	shell: bash  
```

The first test prints the output with a '\n' delimiter but the second on prints an empty string.

![image](https://user-images.githubusercontent.com/8370550/206911105-44e98818-c9c5-418f-9ebf-519fa20f70c1.png)

**Expected behavior**
The value of the output should be printed.

The [repo](https://github.com/martijnvanschie/create-dotnet-versions-action) is open so for any additional info please check there to prevent lots of copy pasting here :)
