### ISSUE TITLE
make reference accessible in reusable workflow 

### ISSUE THREAD

**Issue by kagahd** [actions/toolkit#1264]
**Describe the enhancement**

A reusable workflow should be able to access the reference that it was called for.

**Context**

A reusable workflow in public repos may be [called by appending a reference](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow) which can be a SHA, a release tag, or a branch name, as for example:
`{owner}/{repo}/.github/workflows/{filename}@{ref}`

Githubs [documentation](https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview) states:

> When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow.

**The problem**

Since the github context is always associated with the caller workflow, the reusable workflow cannot access the reference, for example the tag `v1.0.0`. However, knowing the reference is important when the reusable workflow needs to checkout the repository in order to make use of composite actions.

**Code snippet**

Assume that the caller workflow is being executed from within the `main` branch and calls the ref `v1.0.0.` of a reusable workflow:

```
name: Caller workflow

on:
  workflow_dispatch:

jobs:
  caller:
    uses: owner/public-repo/.github/workflows/reusable-workflow.yml@v1.0.0

```

Here is the reusable workflow that uses a composite action:

```
name: reusable workflows
on:
  workflow_call:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          repository: owner/public-repo
          ref: ${{ github.ref_name }}

      - name: composite action
        uses: ./actions/my-composite-action
```
In the above code snippet, `${{ github.ref_name }}` is `main` instead of `v1.0.0` because github context is always associated with the caller workflow. Therefore, the composite actions code is based on `main` and not on `v1.0.0`.

**Proposal**

Introduce a new github context variable `caller_ref` which reflects the reference indicated by the caller.
The reusable workflow could then use it as follows:

```
name: reusable workflows
on:
  workflow_call:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          repository: owner/public-repo
          ref: ${{ github.caller_ref }}

      - name: composite action
        uses: ./actions/my-composite-action
```

Now the composite action would be using `v1.0.0.` as indicated by the caller.

**Comment by cbrzn** [comment]
I have the same issue, and would love some help!

**Comment by mjhipp** [comment]
I am also interested in a solution for this. My use case is I have a repository within my org where I put shared workflows as well as composite actions. I often want to use composite actions within my reusable workflow in the same repository.

```
mjhipp/shared-actions
├── actions
│   └── my-composite-action
│       └── action.yml
└── workflows
    └── my-reusable-workflow.yml
```

```yaml
name: My Reusable Workflow
on:
  workflow_call:
jobs:
  my-reusable-workflow:
    runs-on: ubuntu-latest:
    steps:
      - uses: mjhipp/shared-actions/actions/my-composite-action@{???}
```

I would like to use whatever version I am using for the shared workflow for the called composite action, from the same repo as the called workflow.
I could use `'main'`, but I like to pin version tags in my actions for safety.

**Comment by dstuck** [comment]
Presumably the github.job_workflow_sha which is "For jobs using a reusable workflow, the commit SHA for the reusable workflow file" should solve this but it appears that this variable isn't ever populated: https://github.com/actions/runner/issues/2417

**Comment by GustavoKatel** [comment]
> I am also interested in a solution for this. My use case is I have a repository within my org where I put shared workflows as well as composite actions. I often want to use composite actions within my reusable workflow in the same repository.
> 
> I see that you can do this with reusable workflows, but not yet composite actions: https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
> 
> ```
> mjhipp/shared-actions
> ├── actions
> │   └── my-composite-action
> │       └── action.yml
> └── workflows
>     └── my-reusable-workflow.yml
> ```
> 
> ```yaml
> name: My Reusable Workflow
> on:
>   workflow_call:
> jobs:
>   my-reusable-workflow:
>     runs-on: ubuntu-latest:
>     steps:
>       - uses: mjhipp/shared-actions/actions/my-composite-action@{???}
> ```
> 
> I would like to use whatever version I am using for the shared workflow for the called composite action, from the same repo as the called workflow. I could use `'main'`, but I like to pin version tags in my actions for safety.

I have the same use case and having this implemented would be great for pinning version between the reusable and the composite action

**Comment by cezar-tech** [comment]
Also having this need in my enterprise

**Comment by apascual** [comment]
This is a basic feature need for using reusable workflows. We need a way to keep reusable workflows and the rest of the associated scripting in the same repository so we can version or do branch development. Please, provide a solution to access some context of the reused workflow, ideally access to local files and current branch/tag.

**Comment by lcharest-godaddy** [comment]
Piling on. My org really needs this.

**Comment by carloseduardosx** [comment]
I'm also interested in a solution for this.

My org has a central repo with our Reusable Workflows and Shared Action, and it would be essential for us to call the Shared Action using the same revision of the Reusable Workflow.

**Comment by corest** [comment]
+1 for this
For now I came up with workaround I'm sharing below.

So I have repository `org/workflows` with structure:
```
.github/workflows/shared.yml
actions/action1
actions/action2
```

`.github/workflows/shared.yml` is using `action/action1` and `action/action2` actions inside via e.g. `uses: ./action/action`.

Repository `app` calls shared workflow via `uses: org/workflows/.github/workflows/shared.yml@v1.0.0`.
So we need to know value `v1.0.0` in shared workflow to properly checkout reference with local actions.

Here is how it is done in `.github/workflows/shared.yml`:

```
jobs:

  action1:
    name: Extract metadata
    runs-on: ubuntu-latest
    steps:

      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get workflow reference
        id: workflows-ref
        run: |
          workflow=${{ github.event.workflow }} # get workflow name
          ref=$(cat ${workflow} | grep shared.yml | cut -d"@" -f2) # here `shared.yml` is the name of shared workflow where local actions are used
          echo "ref=${ref}" >> ${GITHUB_OUTPUT} # write into outpu

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.workflows-ref.outputs.ref }} # use ref
          repository: org/workflows
          token: ${{ secrets.CIJOBTOKENWRITE }}
          path: workflows # checkout into separate folder

      - name: action1
        id: action1
        uses: ./workflows/actions/action1

```

**Comment by pdmtt** [comment]
I'm facing this problem too. 

Our reusable workflow needs to checkout its own repository in order to execute a Python script. Allowing access to the called workflow repo's reference would enable versioning its behaviour.

Any developments on this? Thanks!

**Comment by shermanericts** [comment]
> The workaround to this problem that we found was the most clean and easy was to simply do a curl request to get the SHA from the workflow run and use that in ref (_https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run_).
> 
> Example (I don't think I missed anything):
> 
> ```
> jobs:
>   Metadata:
>     name: Extract metadata
>     runs-on: ubuntu-latest
>     permissions:
>       actions: read    
>     outputs:
>       caller-sha: ${{ steps.workflows-ref.outputs.caller-sha }}
>     steps:
>       - name: Get workflow reference
>         id: workflows-ref
>         run: |
>           sha=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/<owner>/<repo>/actions/runs/${{ github.run_id }} | jq -r '.referenced_workflows[0] | .sha')
>           echo "caller-sha=$sha" >> $GITHUB_OUTPUT
>   Test:
>     needs: [Metadata]
>     uses: ./.github/workflows/test.yml
>     secrets: inherit
>     with:
>       version: ${{ needs.Metadata.outputs.caller-sha }}          
> ```
> 
> And then in `./.github/workflows/test.yml`:
> 
> ```
> on:
>   workflow_call:
>     inputs:
>       version:
>         required: true
>         type: string
> jobs:
>   Test:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Check out actions
>         uses: actions/checkout@v4
>         with:
>           repository: <repo> 
>           ref: ${{ input.version }}
>           token: <secrets.TOKEN> ##you need a PAT-token with read rights to the repo
> ```

This was a life-saver for me today. Thank you!

**Comment by Ilyes512** [comment]
I don't understand how such obvious requirement is missing... this is one of the first things I immediately needed when extracting workflows and composite actions to the same repo.

It seems like there is not enough [dogfeeding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) happening at Github. :/

**Comment by earlye** [comment]
This is definitely a thing that still matters. We're in the process of building out shared workflows that are composed of, well, composite actions in the same repository, and having to manually specify a branch as we modify those composite actions in the workflow file is tedious and error prone. Would be much better to be able to say:

```
  - uses: {path-to-workflow}/@${{ github.referenced_workflows[0].sha }}
```

**Comment by ckmoga** [comment]
We have reusable workflows to build docker images and deploy microservices. The docker image workflow is triggered when a version is created and we use ${GITHUB_REF#refs/*/} to extract it.
From what people say above, we must write a composite action to handle this before calling the reusable workflow. This is ok when you have few repos but it becomes daunting when you have 40+ microservices.

We currently copy & paste the workflows because there is not much benefit to using the reusable workflows.
Is there is no other way to do this more efficiently, other than composite actions?

**Comment by ckmoga** [comment]
@carlcsaposs-canonical it is possible that I am missing something but I cannot get my release number using `${GITHUB_REF#refs/*/}`
It is empty but in ordinary workflow it is correct

**Comment by ckmoga** [comment]
OK @carlcsaposs-canonical I got it working with `$GITHUB_REF_NAME`. `${{ github.ref }}` throws unknown reference somehow. I think my issue was the curly brackets: `${GITHUB_REF}`

**Comment by stf976** [comment]
> In case it helps anyone, we created a composite action that implements @maxbergs's [solution](https://github.com/actions/toolkit/issues/1264#issuecomment-1770928498)

It's not obvious to me what the advantage of this solution is over directly passing the called workflow repo and ref as workflow inputs. Especially since for the action you need the repo and file name to get the ref.  

The repo and file name of the called workflow might change, hence should not be hard-coded in the called workflow file. 

You already know the repo, ref, and file name in the caller.  So you could pass the repo and file name to the called workflow to execute the action, or just pass repo and ref and skip the action step.

**Comment by dariocurr** [comment]
Hi guys, following this discussion and looking for a solution I created the following basic action to facilitate what @maxbergs provided us: [`dariocurr/checkout-called`](https://github.com/dariocurr/checkout-called).

I hope it will be useful. The only difficult part, IMHO, might be creating the token with the correct set of permissions

**Comment by extend-devx-service** [comment]
@dariocurr Thank you so much for the action! Works perfectly.

Leaving this comment so others know that it works and that they should use it.

**Comment by randallt21** [comment]
@dariocurr Thank you so much for creating this action! Worked perfectly.

Leaving this comment so others know to use it.

**Comment by nvincent-vossloh** [comment]
@dariocurr , @carlcsaposs-canonical both your solutions are very nice, however, it may not work on self-hosted runner where either `pipx` or `jq` is not available :(

**Comment by jhancock93** [comment]
Would be great to see an update from the repository owners here as to whether they will take this up as a new feature...

**Comment by duboisf** [comment]
I recently encountered this issue and I found a workaround that relatively simple. I don't know if this will work for everyone but it works in my use case. It gets an oidc JWT to get the `job_workflow_ref` field, so you need the `id-token: write` permission when calling the workflow.

My use case: I have a reusable workflow and in this workflow I create a PR comment that links to the workflow docs that is simply a markdown file in the same repo as the reusable workflow. I need the tag to link to the correct workflow doc version.

Here's an example reusable workflow that gets the workflow ref with which it was called and only relies on basic utilities (like curl, cut, base64, tr, etc.) so might be more self-hosted runner friendly in most cases (I use a lot of self-hosted runners). Full example in duboisf/get-reusable-workflow-reference#3:

```yaml
name: Example workflow that can get it's own reference
on:
  push:
  pull_request:
  workflow_call:

jobs:
  Example:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Needed to get the called workflow reference
      id-token: write
    steps:
      - name: Get called workflow reference
        run: |
          JWT=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          PAYLOAD=$(echo "$JWT" | cut -d '.' -f 2 | base64 -d 2>/dev/null || true)

          WORKFLOW_FULL_REF=$(
            echo "$PAYLOAD" \
              | grep -o '"job_workflow_ref":"[^"]*"' \
              | cut -d':' -f2 \
              | cut -d'@' -f2 \
              | tr -d '"'
          )

          echo "WORKFLOW_FULL_REF=$WORKFLOW_FULL_REF"

          case $WORKFLOW_FULL_REF in
            refs/heads/*)
              WORKFLOW_REF=${WORKFLOW_FULL_REF#refs/heads/}
              ;;
            refs/tags/*)
              WORKFLOW_REF=${WORKFLOW_FULL_REF#refs/tags/}
              ;;
            refs/pull/*/merge)
              # exception: we got triggered by a pull request, the ref is the base branch
              WORKFLOW_REF=$GITHUB_HEAD_REF
              ;;
          esac

          echo "::notice ::WORKFLOW_FULL_REF=$WORKFLOW_FULL_REF"
          echo "::notice ::WORKFLOW_REF=$WORKFLOW_REF"

          echo "WORKFLOW_REF=$WORKFLOW_REF" | tee -a $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: duboisf/get-reusable-workflow-reference
          ref: ${{ env.WORKFLOW_REF }}

      - name: Run script from called workflow
        run: |
          ./scripts/example.sh
```

And here's how I call it:

```yaml
name: Call workflow example

on:
  pull_request:

jobs:

  CallWorkflow:
    permissions:
      contents: read
      id-token: write
    uses: duboisf/get-reusable-workflow-reference/.github/workflows/example.yml@v1
```

Output:

![image](https://github.com/user-attachments/assets/117d8688-4980-4b2b-b4bb-d7b0ea98aca1)

**Comment by dariocurr** [comment]
> I recently encountered this issue and I found a workaround that's relatively simple. I don't know if this will work for everyone but it works in my use case. It gets an oidc JWT to get the `job_workflow_ref` field, so you need the `id-token: write` permission when calling the workflow.
> 
> My use case: I have a reusable workflow and in this workflow I create a PR comment that links to the workflow docs that is simply a markdown file in the same repo as the reusable workflow. I need the tag to link to the correct workflow doc version.
> 
> Here's an example reusable workflow that gets the workflow ref with which it was called and only relies on basic utilities (like curl, cut, base64, tr, etc.) so might be more self-hosted runner friendly in most cases (I use a lot of self-hosted runners). Full example in [duboisf/get-reusable-workflow-reference#3](https://github.com/duboisf/get-reusable-workflow-reference/pull/3):
> 
> ```yaml
> name: Example workflow that can get it's own reference
> on:
>   push:
>   pull_request:
>   workflow_call:
> 
> jobs:
>   Example:
>     runs-on: ubuntu-latest
>     permissions:
>       contents: read
>       # Needed to get the called workflow reference
>       id-token: write
>     steps:
>       - name: Get called workflow reference
>         run: |
>           JWT=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
>           PAYLOAD=$(echo "$JWT" | cut -d '.' -f 2 | base64 -d 2>/dev/null || true)
> 
>           WORKFLOW_FULL_REF=$(
>             echo "$PAYLOAD" \
>               | grep -o '"job_workflow_ref":"[^"]*"' \
>               | cut -d':' -f2 \
>               | cut -d'@' -f2 \
>               | tr -d '"'
>           )
> 
>           echo "WORKFLOW_FULL_REF=$WORKFLOW_FULL_REF"
> 
>           case $WORKFLOW_FULL_REF in
>             refs/heads/*)
>               WORKFLOW_REF=${WORKFLOW_FULL_REF#refs/heads/}
>               ;;
>             refs/tags/*)
>               WORKFLOW_REF=${WORKFLOW_FULL_REF#refs/tags/}
>               ;;
>             refs/pull/*/merge)
>               # exception: we got triggered by a pull request, the ref is the base branch
>               WORKFLOW_REF=$GITHUB_HEAD_REF
>               ;;
>           esac
> 
>           echo "::notice ::WORKFLOW_FULL_REF=$WORKFLOW_FULL_REF"
>           echo "::notice ::WORKFLOW_REF=$WORKFLOW_REF"
> 
>           echo "WORKFLOW_REF=$WORKFLOW_REF" | tee -a $GITHUB_ENV
> 
>       - uses: actions/checkout@v4
>         with:
>           repository: duboisf/get-reusable-workflow-reference
>           ref: ${{ env.WORKFLOW_REF }}
> 
>       - name: Run script from called workflow
>         run: |
>           ./scripts/example.sh
> ```
> 
> And here's how I call it:
> 
> ```yaml
> name: Call workflow example
> 
> on:
>   pull_request:
> 
> jobs:
> 
>   CallWorkflow:
>     permissions:
>       contents: read
>       id-token: write
>     uses: duboisf/get-reusable-workflow-reference/.github/workflows/example.yml@v1
> ```
> 
> Output:
> 
> ![image](https://private-user-images.githubusercontent.com/169247/389292651-117d8688-4980-4b2b-b4bb-d7b0ea98aca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjExMjMsIm5iZiI6MTczMjUyMDgyMywicGF0aCI6Ii8xNjkyNDcvMzg5MjkyNjUxLTExN2Q4Njg4LTQ5ODAtNGIyYi1iNGJiLWQ3YjBlYTk4YWNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNzQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWM0M2I0MmM4OTg0MTkwNjYwNmFmZWUxMGMyYTBlMGNkMjAwMDYwMTI0NzIyNTQ1NjE2ZTZiNDFiYjk4ZDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YLQQ0z6Bam7BkIPMn38XQ2j78w0X-4XUudzpfwoIf98)

Thank you for the wonderful cue. Implemented in the [dev branch](https://github.com/dariocurr/checkout-called/tree/dev). Currently testing it

**Comment by CMCDragonkai** [comment]
I would argue that the reusable workflow should have be a convenient way of referencing its own repository that it came from without having to call outside APIs or even having to check it out again. Afterall how the reusable workflow come into existence anyway? It had to be checked out by the calling workflow, so its repo must still be somewhere.

**Comment by hrimhari** [comment]
Hate to do this, but.. me too!

**Comment by dannystaple** [comment]
> +1 for this For now I came up with workaround I'm sharing below.
> 
> So I have repository `org/workflows` with structure:
> 
> ```
> .github/workflows/shared.yml
> actions/action1
> actions/action2
> ```
> 
> `.github/workflows/shared.yml` is using `action/action1` and `action/action2` actions inside via e.g. `uses: ./action/action`.
> 
> Repository `app` calls shared workflow via `uses: org/workflows/.github/workflows/shared.yml@v1.0.0`. So we need to know value `v1.0.0` in shared workflow to properly checkout reference with local actions.
> 
> Here is how it is done in `.github/workflows/shared.yml`:
> 
> ```
> jobs:
> 
>   action1:
>     name: Extract metadata
>     runs-on: ubuntu-latest
>     steps:
> 
>       - name: Checkout calling repository
>         uses: actions/checkout@v4
>         with:
>           fetch-depth: 1
> 
>       - name: Get workflow reference
>         id: workflows-ref
>         run: |
>           workflow_ref=${{ github.workflow_ref }}
>           repository="${{ github.repository }}/"
>           repo_ref="@${{ github.ref }}"
>           workflow_path=${workflow_ref#"$repository"}
>           workflow_path=${workflow_path%"$repo_ref"}
> 
>           ref=$(cat ${workflow_path} | grep pull-request-java-app | cut -d"@" -f2)
>           echo "ref=${ref}" >> ${GITHUB_OUTPUT}
> 
>       - name: Checkout workflows
>         uses: actions/checkout@v4
>         with:
>           ref: ${{ steps.workflows-ref.outputs.ref }} # use ref
>           repository: org/workflows
>           token: ${{ secrets.CIJOBTOKENWRITE }}
>           path: workflows # checkout into separate folder
> 
>       - name: action1
>         id: action1
>         uses: ./workflows/actions/action1
> ```

This almost worked, until we found a repo that had a comment against the action ref.
Our adaptation also allows the same reusable workflow to be dogfooded/tested within the same repo:
```bash
          # This variable is manipulated by the two expansions
          workflow_ref=${{ github.workflow_ref }}

          # Delete the repository from the front of worklow ref
          workflow_path="${workflow_ref#"${{ github.repository }}/"}"

          # Delete the rep ref from anywhere in the workflow path
          workflow_path="${workflow_path%"@${{ github.ref }}"}"

          caller_reference="$(grep "${workflow_name}" "${workflow_path}")"

          ## If this starts with ./, then just use the current ref
          echo "caller reference=${caller_reference}"
          if [[ "${caller_reference}" == *"./.github/workflows"* ]]; then
            sha="${{ github.ref }}"
          else
            sha="$(echo "${caller_reference}" | cut -d"@" -f2)"
            # trim anything after the version term (spaces)
            sha="$(echo "${sha}" | cut -d" " -f1)"
          fi
          echo "sha=${sha}" >> "${GITHUB_OUTPUT}"
```

Still, that is a lot of boiler plate to be able to use scripts/other components from within a reusable workflow.

**Comment by kaedwen** [comment]
This is such a small thing to fix which many people would benefit from. Not sure why this issue is still there after years! This really puts GitHub Actions in a bad light and slows down its adoption.

**Comment by dariocurr** [comment]
> This is such a small thing to fix which many people would benefit from. Not sure why this issue is still there after years! This really puts GitHub Actions in a bad light and slows down its adoption.

I know and agree with you. While waiting for GitHub to wake up, you can use my workaround [checkout-called](https://github.com/dariocurr/checkout-called)

**Comment by dkfellows** [comment]
The new [self-referencing syntax](https://github.blog/changelog/2026-07-30-reference-same-repository-actions-with-self-repository-syntax/) makes this a whole lot easier. I have an internal action like this (in `.github/internal-actions/checkout-self/action.yml`):
```yml
name: "Internal: Checkout Self"
description: Checks out this repository.
inputs:
  path:
    description: Where to put the checkout.
    required: true
  sparse-checkout:
    description: What part of the repository to check out.
    required: true
  repository:
    description: What repository to check out.
    default: ${{ github.action_repository }}
  ref:
    description: What ref to check out.
    default: ${{ github.action_ref }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: ${{ inputs.path }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        persist-credentials: false
```
And then I call it like this:
```yml
      - name: Checkout configuration files
        uses: $/.github/internal-actions/checkout-self
        with:
          path: .some-path
          sparse-checkout: .github/config-files
```

Be aware that the `repository` and `ref` ***need to be bound as inputs*** like that because of time-of-substitution bugs. (I guess you could also use a little scripted step, but that introduces another visible workflow sub-step. What I've done works...)
