### ISSUE TITLE
core.setFailed and core.error won't fail the workflow

### ISSUE THREAD

**Issue by lslzl3000** [actions/toolkit#1385]
I am  test a simple script with github actions

```yml
name: CI test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Setup node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: pnpm
    - name: Install deps
      run: pnpm install
    - name: Test in Electron
      run: pnpm run test
```

and my node script is easy
```js
const core = require('@actions/core');

ipc.on('log', (log) => {        
    if(log === 'pass'){
        console.log('CI pass')
    }else{
        core.setFailed(`CI not pass`);
    }
})
ipc.on('error', (log) => {
    core.error(log);
})
```

it shows errors in actions log, but the workflow still finished and marked as `succeeded`
<img width="1409" alt="Screenshot 2023-03-26 at 14 19 28" src="https://user-images.githubusercontent.com/3398981/227759078-76fa261f-190a-4f03-807f-9d3f970f5344.png">

Do I miss something?
