### ISSUE TITLE
Allow regex in event path

### ISSUE THREAD

**Issue by florianwiech** [actions/toolkit#140]
It would be great if it would be possible to define the path event on an arbitrary amount of sub-directories:

```yaml
on:
  push:
    paths:
      # '*' matches any character except '/'
      - 'sub-project/**'
```

- [Syntax Docs](https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requestpaths)
