### ISSUE TITLE
Simple on.push.paths settings not being applied?

### ISSUE THREAD

**Issue by ArnaudRinquin** [actions/toolkit#142]
Hi,

We're running a monorepos and setup a handful of workflows targeting specific paths, such as:

```
name: API checks

on:
  push:
    paths:
      - api/*
```

The issue we're facing is that all workflows run whenever we push, regardless of the actual path changes.

Something that might explain: our main branch isn't master but another one. Any idea?
