### ISSUE TITLE
core.addPath() can break $PATH in the openSUSE container

### ISSUE THREAD

**Issue by ueokande** [actions/toolkit#1680]
**Describe the bug**

When I use `core.addPath()` in the openSUSE container, it breaks `$PATH` in the container and any command fails with the following error:

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
```

Here is a minimal reproduction repository: https://github.com/ueokande/actions-add-path.  The [action script](https://github.com/ueokande/actions-add-path/blob/master/src/index.mjs) calls `core.addPath()` with the custom path.  The GitHub Action manifest to reproduce the error is the following:

```yaml
name: 'ci'
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        container:
          - fedora
          - debian
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: id
      - uses: ueokande/actions-add-path@master
      - run: id
```

It works as expected in the Fedora and Debian containers, but openSUSE does not work.

**Expected behavior**
The `core.addPath()` should work in the openSUSE container as other distributions.

**Screenshots**
![Screenshot 2024-03-02 at 10-10-04 use root action · ueokande_actions-add-path@c63ed73](https://github.com/actions/toolkit/assets/534166/77ad76ba-886d-46da-b48d-ece551a6f069)
[Job result](https://github.com/ueokande/actions-add-path/actions/runs/8121979717/job/22200945987)

**Additional context**
