### ISSUE TITLE
undici not in dependencies

### ISSUE THREAD

**Issue by mehulkar** [actions/toolkit#1684]
undici is used in `@actions/github`, but it isn't in dependencies:
- https://github.com/actions/toolkit/blob/ef77c9d60bdb03700d7758b0d04b88446e72a896/packages/github/src/internal/utils.ts#L4
- https://github.com/actions/toolkit/blob/ef77c9d60bdb03700d7758b0d04b88446e72a896/packages/github/package.json#L40-L48

**Comment by matthieu-crouzet** [comment]
For the one using yarn berry you can fix this issue in your .yarnrc.yml by adding
```yml
packageExtensions:
  "@actions/github@^6.0.0":
    dependencies:
      "undici": "^5.25.4"
```
