### ISSUE TITLE
`core.summary.addCodeBlock()` sometimes doesn't render Markdown correctly

### ISSUE THREAD

**Issue by Drarig29** [actions/toolkit#1689]
**Describe the bug**

I found a bug with `core.summary.addCodeBlock()`. There is a conflict when mixing:
- `addBreak()`
- A markdown code block starting with a HTML comment
- Two line breaks (`\n\n`) between the HTML comment and the markdown title

**To Reproduce**

```yml
on: push

jobs:
  does-not-work:
    runs-on: ubuntu-latest
    steps:
      # addBreak() + HTML comment + 2 new lines
      - name: Doesn't work
        uses: actions/github-script@v7
        with:
          script: |
            await core.summary
              .addBreak()
              .addCodeBlock(`<!-- some html comment -->\n\n# Title`, 'markdown')
              .write()

  works-1:
    runs-on: ubuntu-latest
    steps:
      # HTML comment + 2 new lines (addBreak() removed, but I want it for spacing)
      - name: Works 1
        uses: actions/github-script@v7
        with:
          script: |
            await core.summary
              .addCodeBlock(`<!-- some html comment -->\n\n# Title`, 'markdown')
              .write()

  works-2:
    runs-on: ubuntu-latest
    steps:
      # addBreak() + HTML comment + 1 new line (but release notes are generated with 2 new lines)
      - name: Works 2
        uses: actions/github-script@v7
        with:
          script: |
            await core.summary
              .addBreak()
              .addCodeBlock(`<!-- some html comment -->\n# Title`, 'markdown')
              .write()

  works-3:
    runs-on: ubuntu-latest
    steps:
      # addBreak() + HTML comment + 2 new lines replaced by 1 new line
      - name: Works 3 (workaround)
        uses: actions/github-script@v7
        with:
          script: |
            await core.summary
              .addBreak()
              .addCodeBlock(
                `<!-- Release notes generated using configuration in .github/release.yml at vX.X.X -->\n\n## What's Changed\n* Some PR by @Drarig29 in https://github.com/foo/bar/pull/123\n\n**Full Changelog**: https://github.com/foo/bar/compare/vX.X.X...vY.Y.Y`
                  .replace('-->\n\n', '-->\n'),
                'markdown'
              )
              .write()
```

**Expected behavior**

The expected behavior is described in the `works-3` job, see screenshot.

I'm using `github.rest.repos.generateReleaseNotes()` to generate the release notes, and I want to put them in a codeblock so that we can copy the changelog and paste it in a PR.

**Screenshots**

Screenshot taken from [here](https://github.com/DataDog/datadog-ci/actions/runs/8279796881):

<img width="1153" alt="image" src="https://github.com/actions/toolkit/assets/9317502/a1cd478f-6d20-4eb0-8151-28e6444a6dcf">
