### ISSUE TITLE
GITHUB_OUTPUT variables do work from workflow but not inside a GitHub action

### ISSUE THREAD

**Issue by de-jcup** [actions/toolkit#1906]
## Description

When I write a key value pair by echo inside a workflow it works. When I use core.setOutput('key1', 'value1') it does not work.

Also the output is completely different.

### Set output with echo - works
Here an example which [uses the described new way of setting outputs by environment variables](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples). This works and the output file is in an expected way:

```yaml
 - name: Print output by worfklow
      id: output_test_by_worfklow
      if: always()
      run: |
        echo "scan-trafficlight=RED" >> "$GITHUB_OUTPUT"  # Test Output 1
        echo "scan-findings-count=1" >> "$GITHUB_OUTPUT"  # Test Output 2

- name: Show all github output files
      id: output_file
      if: always()
      run: |
        echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
        DIRECTORY=$(dirname -- "$GITHUB_OUTPUT")
        # Check if the directory exists
        if [ ! -d "$DIRECTORY" ]; then
          echo "Directory does not exist."
          exit 1
        fi
        # Iterate through each file in the directory
        for FILE in "$DIRECTORY"/*; do
          # Check if the file name starts with "set_output"
          if [[ $(basename "$FILE") == set_output* ]]; then
            echo "----------------------------------------------------------------------------------------------------"
            echo "Contents of $FILE:"
            echo "----------------------------------------------------------------------------------------------------"
            cat "$FILE"
            echo # Add a newline for better readability
          fi
        done
- name: Print Context Information
      if: always()
      env:
        CONTEXT: ${{ toJson(steps) }}
      run: echo "$CONTEXT"
```
After execution I got following:
```
----------------------------------------------------------------------------------------------------
Contents of /runner/_work/_temp/_runner_file_commands/set_output_8c665a1b-cb6b-4962-96ca-3075398fe305:
----------------------------------------------------------------------------------------------------
scan-trafficlight=RED
scan-findings-count=1
```
and the (reduced) context output looks like this
``` json
"output_test_by_worfklow": {
    "outputs": {
      "scan-trafficlight": "RED",
      "scan-findings-count": "1"
    },
    "outcome": "success",
    "conclusion": "success"
  }

```

Means everything is working. Fine.

### Set output via API - DOES NOT WORK
But when I write a custom action an 
use 
```typescript
core.setOutput('scan-trafficlight','RED')
core.setOutput('scan-findings-count','1')
```

it does not work an does behave different (regarding output file).

```yaml
 - name: Print output by custom action
      id: output_test_by_custom_action
      uses: {orgname}/{customActionWhichSetsOutput}
- name: Show all github output files
      id: output_file
      if: always()
      run: |
        echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
        DIRECTORY=$(dirname -- "$GITHUB_OUTPUT")
        # Check if the directory exists
        if [ ! -d "$DIRECTORY" ]; then
          echo "Directory does not exist."
          exit 1
        fi
        # Iterate through each file in the directory
        for FILE in "$DIRECTORY"/*; do
          # Check if the file name starts with "set_output"
          if [[ $(basename "$FILE") == set_output* ]]; then
            echo "----------------------------------------------------------------------------------------------------"
            echo "Contents of $FILE:"
            echo "----------------------------------------------------------------------------------------------------"
            cat "$FILE"
            echo # Add a newline for better readability
          fi
        done
- name: Print Context Information
      if: always()
      env:
        CONTEXT: ${{ toJson(steps) }}
      run: echo "$CONTEXT"
```
After execution I got following:
```
----------------------------------------------------------------------------------------------------
Contents of /runner/_work/_temp/_runner_file_commands/set_output_9550026e-04b7-4a5e-963b-4d7838e73e4d:
----------------------------------------------------------------------------------------------------
scan-trafficlight<<ghadelimiter_12b579a9-fb20-4e41-8b6d-53dd97e57865
RED
ghadelimiter_12b579a9-fb20-4e41-8b6d-53dd97e57865
scan-findings-count<<ghadelimiter_b1042cbc-4b13-4648-851b-83535f96876c
1
ghadelimiter_b1042cbc-4b13-4648-851b-83535f96876c
```
and the (reduced) context output looks like this
``` json
"output_test_by_custom_action": {
    "outputs": {

    },
    "outcome": "success",
    "conclusion": "success"
  }
```
Means: 
1. The output is written not `{key}={value}{os.EOL}` but in a different format
2. The context does not contain output information

##### File direct change did not work
I tried to write the file directly `{key}={value}{os.EOL}` but the 2 keys were still not
visible in context output.

##### Parts inside code
https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L192

```typescript
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
