### ISSUE TITLE
`run` command's arguments split before a period on Windows

### ISSUE THREAD

**Issue by ppalaga** [actions/toolkit#231]
I hope this is the right place to report this issue.

Having a `maven.yml` like the following:

```
name: Java CI

on: [pull_request]

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: ./mvnw clean verify -B -ntp -Dinvoker.streamLogs=true
```

results in the following Maven error 

```
[ERROR] Unknown lifecycle phase ".streamLogs=true". You must specify a valid lifecycle phase or a goal
```

which means that GitHub Actions parse the arguments of `mvnw` command in a wrong way. Apparently, period `.` is interpreted as a delimiter and thus 6 args 

1 clean
2 verify
3 -B 
4 -ntp 
5 -Dinvoker
6 .streamLogs=true

 are passed instead of 5:

1 clean
2 verify
3 -B 
4 -ntp 
5 -Dinvoker.streamLogs=true

This happens only on Windows. The same command works as expected in Linux.

Workaround: enclosing the whole command in apostrophes and the comma containing arg in double quoutes helps:

```
      run: './mvnw clean verify -B -ntp "-Dinvoker.streamLogs=true"'
```
