### ISSUE TITLE
Deprecation warning "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead

### ISSUE THREAD

**Issue by mahaker** [actions/toolkit#267]
**Describe the bug**

When use `issues.createComment()`, deprecation warning appeared.

```
Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead
    at /home/runner/work/_actions/actions/github-script/0.3.0/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:71:26
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as createComment] (/home/runner/work/_actions/actions/github-script/0.3.0/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:67:26)
    at eval (eval at main (/home/runner/work/_actions/actions/github-script/0.3.0/main.js:19:14), <anonymous>:3:15)
    at main (/home/runner/work/_actions/actions/github-script/0.3.0/main.js:20:24)
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/0.3.0/main.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  name: 'Deprecation'
}
```

**To Reproduce**

I confirmed on github actions.

1. Create a .github/workflow/comment.yml. Its following [this](https://github.com/actions/github-script#comment-on-an-issue).
   ```yml
   name: Say Hello!
   
   on:
     issues: {types: opened}

   jobs:
     comment:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/github-script@0.3.0
            with:
              github-token: ${{secrets.GITHUB_TOKEN}}
              script: |
                github.issues.createComment({...context.issue, body: '👋 Thanks for reporting!'})
   ```
1. Create a issue.
1. See `Actions`

**Expected behavior**

No warning appeared.

**Screenshots**

![スクリーンショット 2019-12-18 18 27 50](https://user-images.githubusercontent.com/13829678/71073668-28cc3680-21c4-11ea-9fef-9a4ce1bfb4f7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

`number` property is deprecated since @octokit/rest v19.20. https://github.com/octokit/rest.js/pull/1316

**Comment by mahaker** [comment]
I expect `issue()` getter must returns `issue_number`.

https://github.com/actions/toolkit/blob/f79897266ee00417d0fd7ce49ab61982045e8673/packages/github/src/context.ts#L42

**Comment by joshmgross** [comment]
This isn't necessarily an issue with `@actions/github` or even `actions/github-script`.

`number` is the correct field for `Issue` in the API: https://developer.github.com/v3/issues/

Create Comment API wants `issue_number` instead of `number`, see https://developer.github.com/v3/issues/comments/#create-a-comment

`number` is deprecated in `@Octokit/Rest` [here](https://github.com/octokit/rest.js/blob/d40b2e37da87e78a9d299426254d6adc4b0d6ccb/plugins/rest-api-endpoints/routes.json#L1333)

Updating the sample removes the deprecation warning 
```yaml
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner, repo: context.issue.repo, issue_number: context.issue.number }
            github.issues.createComment({...issue, body: '👋 Thanks for reporting!'})
```
See https://github.com/joshmgross/github-script-testing/runs/369213935?check_suite_focus=true#step:2:5
