### ISSUE TITLE
core.exportVariable does not set variable with underscores on MacOS

### ISSUE THREAD

**Issue by SeyfSV** [actions/toolkit#323]
**Describe the bug**
core.exportVariable does not set variable with underscores (ex. ENV_VARIABLE) on macos-latest runner.
It works good on ubuntu-latest and windows-latest.

**To Reproduce**
Create action and call core.exportVariable('ENV_VARIABLE', 'test').
Run Actions within macos-latest  runner

**Expected behavior**
ENV_VARIABLE is set

**Comment by thboop** [comment]
Hey @SeyfSV I've been unable to reproduce this issue. Do you have a link to your run and action, or could you provide more information?

I created a custom action with the following typescript:
```
import * as core from '@actions/core'

async function run(): Promise<void> {
  try {
    core.exportVariable('ENV_VARIABLE', 'test')
    core.info('Ran the action')
  } catch (error) {
    core.setFailed(error.message)
  }
}

run()
```
Using `@actions/core` 1.2.2.

I then used the following workflow file
```yaml
name: Test CI

on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: thboop/typescript-action@master # your action should go here
      - run: echo $ENV_VARIABLE
        shell: bash
```

On all three platforms, the second step output "test" as expected.
