### ISSUE TITLE
Unziping tools from cache on linux freezes the entire workflow in interactive mode waiting for user input

### ISSUE THREAD

**Issue by Veetaha** [actions/toolkit#456]
**Describe the bug**
When unzipping the files from the tool cache `unzip` util is run in interactive mode and when there already exists a file in the target dir it freezes the entire workflow waiting for some user input which is ridiculous.

**To Reproduce**
1. Create a workflow with `actions-rs/install` which uses the tool cache and instal `sccache` with it
and also cache the `~/.cargo/bin` dir where `sscache` utility is installed
```yml
    -  uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-bin
    -   uses: actions-rs/install@v0.1.2 
        with:
          crate: sccache
          use-tool-cache: true
```
2. Run this workflow a couple of times.

**Expected behavior**
I expect that the workflow is run without freezing on unzipping step. It should either replace the existing file or leave it like it is without unzipping, but never freeze the execution waiting for the user input.

**Screenshots**
![image](https://user-images.githubusercontent.com/36276403/81925932-dca5e680-95e9-11ea-8794-45ba746bb798.png)

**Additional context**
Related PRs: 
 - https://github.com/actions/toolkit/pull/418

Related issues:
- https://github.com/actions-rs/install/issues/3, 
- https://github.com/actions-rs/tool-cache/issues/5
