### ISSUE TITLE
Allow updating an existing cache

### ISSUE THREAD

**Issue by davidsbond** [actions/toolkit#505]
GitHub actions supports caching across builds which is super powerful. However, once a cache has been saved it can no longer be modified. While this is fine for most scenarios where you need the cache there are a few times when you would like to update it.

I created this PR on the actual cache action to allow updating a cache when providing it in configuration:

https://github.com/actions/cache/pull/353

I created it after reading the related issue:

https://github.com/actions/cache/issues/342

However, it seems like something either needs to change in this package or server-side on the actions cache.

My use-case for wanting to update a cache is when using GitHub actions in golang projects. Go supports a test cache which allows tests to be skipped if the code they use has not changed, which can significantly improve test times (especially in large projects). Each time I run my tests, I'd like to maintain a single cache for tests, that way, when a run completes I can update the cache and all my workflows share a single test cache

There are some extra use-cases describe on the issue above.

**Comment by smorimoto** [comment]
I would also like to support this proposal.

**Comment by half2me** [comment]
I need this too

**Comment by eLarocque** [comment]
same

**Comment by akmjenkins** [comment]
I figured out a hack to get this working simply with the existing cache package, simply because this (and multiple related PRs/issues) have been hanging out there so long.

The trick is to create two cache actions - one that **never gets hit** (thus always resulting in a save at the end) and a second that restores something valid. The one that never gets hit needs to be first (so it's save gets ran last).

I ran into the exact same issues as the OP (but with a node project) where testing and linting gets updated during the run, but should still be restorable from previous runs. This is how it works:

```

      # This gross hack forces us to always update the lint/jest caches
      - name: Cache Lint/Jest Hack
        uses: actions/cache@v2
        with:
          path: |
            **/.eslintcache
            **/.jest
          # using github.sha prevents this from ever getting hit
          key: ${{ runner.os }}-eslint-jest-${{ github.sha }}        

      - name: Cache Lint/Jest
        uses: actions/cache@v2
        with:
          path: |
            **/.eslintcache
            **/.jest
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-eslint-jest
          restore-keys: |
            # the restore key must match the cache key from the first action, **not** this one
            ${{ runner.os }}-eslint-jest

```

**Comment by CAMOBAP** [comment]
+

**Comment by Blissful89** [comment]
#poke

**Comment by hyperxpro** [comment]
+1

**Comment by DenizUgur** [comment]
+1

**Comment by kazanture** [comment]
+1

**Comment by YegorMedvedev** [comment]
In the meantime, here's a workaround that I use:
```yml
- name: Get cache
  uses: actions/cache@v3
  with:
    path: ... # a list of cache paths
    key: ${{ runner.os }}-my-cache-${{ github.head_ref }}-${{ hashFiles(...for example yarn.lock...) }}

- name: Do something to change a cache
  run: ...

- name: Enforce cache update for a local NX cache
  run: |
    STATE_CACHE_KEY="${{ runner.os }}-my-cache-${{ github.head_ref }}-${{ hashFiles(...) }}"
    echo "STATE_CACHE_KEY=${STATE_CACHE_KEY}" >> $GITHUB_ENV
```

**Comment by arpanrecme** [comment]
+1

**Comment by bexsoft** [comment]
+1

**Comment by nnsay** [comment]
+1

**Comment by dsame** [comment]
Updating the cache is supposed to be done with [restore-keys](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)

This input allows to restore the cache even if it is not fully matched. And to generate the new key to update the cache do one of:

1. include the changing file into `${{ hashFiles(...) }}`
2. [set output](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) of the previous step and include it into the `key`

**Comment by isaacbowen** [comment]
@dsame [This](https://github.com/actions/toolkit/issues/505#issuecomment-1650290249) is exactly what I was missing. Thank you for sharing! Super super super helpful. ❤️

**Comment by pauldraper** [comment]
@dsame's workaround is the best available currently, though it does have problems.

Github hard-limits repos to 10GB of caches. So creating lots of caches can push other less-frequent-but-helpful caches to deletion. Whereas if you could update/replace an existing cache, that wouldn't happen.

**Comment by lcswillems** [comment]
On Gitlab or a lot of other different CI/CD tools, this is built-in :cry: Such a pain not to have this!

**Comment by trallnag** [comment]
I came across this documentation that uses artifacts across workflow runs as a workaround for this: https://github.com/renovatebot/github-action?tab=readme-ov-file#persisting-the-repository-cache

**Comment by hamistao** [comment]
+9. Need this to cache a vulnerability database to improve the performance and reliability of our CI workflow.

**Comment by mabar** [comment]
Using less specific key for loading cache than for saving (e.g. `example-1` for saving and `example-` for loading) is the correct solution. Simply adding run ID to the key is enough to keep the cache always up to date.

Cache can currently be restored from the default branch - that allows use of cache for newly created PRs and branches from the start. Updating an existing cache would require removal of that feature because e.g. updating cache in third party PR and using it on master would eventually result in bad consequences.

Problem is that it is not explained in the documentation.

Secondary, cache size is limited and there is no way how to remove less useful and outdated cache that is likely to be never used again, causing more useful cache to be deleted.
I would e.g. like to have an ability to delete branch-specific cache when it is deleted and delete cache, that matches restore-keys but has a newer version.

Also having a button for deleting all the cache would be quite helpful for debugging cache-related issues.

**Comment by AlexanderRichert-NOAA** [comment]
Any update on this, including plans to implement? It would be very useful to be able to, say, set `overwrite: true` for my cache action and update in place as opposed to having to separately delete the cache each time.

**Comment by Dracks** [comment]
Maybe is it possible to use the separated actions to allways save the cache? see: https://github.com/actions/cache/tree/main/save#always-save-cache

**Comment by StaNov** [comment]
+1

There is no way how to reasonably cache gradle build-cache without creating a new cache for each action run.

**Comment by Farenheith** [comment]
In an action that build and test, I generate some turbo and jest caches that are very useful to cache in github to make action faster, and the model where I could update the cache in place per branch would be ideal.
A workaround I did that worked for me was, in the build and test reusable action:

* Use restore step to get cache
```
- name: Restore build artifacts cache
      uses: actions/cache/restore@v4
      id: build-cache
      with:
        path: |
          .turbo
          .jest
          libs/*/.turbo
          libs/*/.jest
        key: build-${{ runner.os }}-${{ github.ref_name }}
        restore-keys: |
          build-${{ runner.os }}-main
          build-${{ runner.os }}-
```
* Upload artifacts
```
- name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          .turbo
          .jest
          libs/*/.turbo
          libs/*/.jest
        retention-days: 1
        if-no-files-found: ignore
        include-hidden-files: true
```

Then, in another reusable action that runs in sequence in the main action:

* Download artifacts:
```
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .
      continue-on-error: true
```
* Delete current cache
```
- name: Save updated build cache
      shell: bash
      run: |
        CACHE_KEY="build-${{ runner.os }}-${{ github.ref_name }}"
        echo "Cache key: $CACHE_KEY"

        gh cache list --key "$CACHE_KEY" --json key,id | jq -r '.[].id' | while read cache_id; do
          if [ -n "$cache_id" ]; then
            echo "Deleting cache ID: $cache_id"
            gh cache delete "$cache_id" || echo "Failed to delete cache $cache_id (may not exist)"
          fi
        done
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      continue-on-error: true
```
* Upload artifacts as new cache
```
    - name: Save build cache
      if: env.ARTIFACTS_FOUND == 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          .turbo
          .jest
          libs/*/.turbo
          libs/*/.jest
        key: build-${{ runner.os }}-${{ github.ref_name }}
      continue-on-error: true
```

This secondary reusable action always run, it doesn't matter if build and test fails,
