### ISSUE TITLE
Unable get env variables from yml

### ISSUE THREAD

**Issue by sorxrob** [actions/toolkit#512]
**Describe the bug**
I was trying to get the authenticated user details using `@actions/github` and `'@actions/core'` but I'm getting `Parameter token or opts.auth is required`. Here's my code:

***update-readme.yml***

```yml
name: Update README

on:
  push:

jobs:
  echo-input:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run update-readme
        env:
          MY_TOKEN: ${{ secrets.README_TOKEN }}
          CI: true
```

***test.js***

```javascript
const github = require('@actions/github'); // ^4.0.0
const core = require('@actions/core'); // ^1.2.4

async function run() {
    try {
        const token = core.getInput('MY_TOKEN'); // This results to undefined.

        const octokit = github.getOctokit(token);

        const { data: user } = await octokit.users.getAuthenticated();

        console.log(user);
    } catch (err) {
        core.setFailed(err);
    }
}

run();
```

**Desktop:**
 - OS: Catalina
 - Browser: Chrome
 - Version: 83.0.4103.116 

**Additional Context**

I'm pretty sure I set the `README_TOKEN` secret in the repo.

Doing `process.env.MY_TOKEN` works though. But not `core.getInput('MY_TOKEN')`.
