### ISSUE TITLE
Getting the job_id with toolkit

### ISSUE THREAD

**Issue by 8398a7** [actions/toolkit#550]
**Describe the enhancement**
https://docs.github.com/en/rest/reference/actions#get-a-job-for-a-workflow-run
I want to use the above API from toolkit.
toolkit is currently unable to retrieve the information corresponding to the `job_id`.

**Code Snippet**

Now we need to use the list API to identify the job_id in the executed job and combine it with name(context.job, GITHUB_JOB_NAME) to identify the job.

```typescript
    const resp = await github.actions.listJobsForWorkflowRun({
      owner: context.repo.owner,
      repo: context.repo.repo,
      run_id: context.runId,
    });
    const currentJob = resp?.data.jobs.find(job => job.name === context.job);
```

This works for simple jobs, but is more complicated when matrix is used.
The reason for this is that the name will be different from the context.job.

```yaml
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        flavor: [dev, prod]
```

In the above yaml, the job name is `build(ubuntu-18.04, dev)`, `build(ubuntu-18.04, prod)`, `build(ubuntu-20.04, dev)`, ` `build(ubuntu-20.04, prod)`. Because context.job is a `build` job, the method to identify it from the result of the list is complicated.

It is simple to add information like `context.jobId`.

```typescript
    const resp = await this.github?.actions.getJobForWorkflowRun({
      owner: context.repo.owner,
      repo: context.repo.repo,
      job_id: context.jobId,
    })
    const currentJob = resp?.data
```

The job_id information appears to be nowhere to be found, so it may be more than a fix for the toolkit itself.

**Additional information**

This may not be the issue that opens the issue here.
In that case, I'm sorry.

**Comment by polarathene** [comment]
It looks like you could [reference a job by id](https://docs.github.com/en/rest/reference/actions#list-jobs-for-a-workflow-run)?

Does this not work?:

```js
const currentJob = resp?.data.jobs.find(job => job.id === context.github.job);
```

There is the [`job` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-context), but it lacks information on the `job` object. So you'd need to get that information and inspect it.

If you need the job id of the current job however, [`context.github.job` provides that](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context).

**Comment by qoomon** [comment]
You could use `qoomon/actions--context@v4` action to add additional environment variables.It will work also with matrix jobs and within reusable workflows.

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    environment: playground
    steps:
      - uses: qoomon/actions--context@v4
      - run: |
          echo "Job Log URL:    ${GITHUB_JOB_URL}"
          echo "Environment:    ${GITHUB_ENVIRONMENT}"
          echo "Deployment URL: ${GITHUB_DEPLOYMENT_URL}"
```

This action determines the current job by listing all job of current workflow with current run id and then finds current job by matching the runner name or id.

Source: https://github.com/qoomon/actions--context
