### ISSUE TITLE
needs.<job id>.result is using steps conclusion instead of outcome

### ISSUE THREAD

**Issue by tleveque69** [actions/toolkit#581]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.  

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#contacting-support)

If your issue is relevant to this repository, please include the information below:

**Describe the bug**
I've been trying to use needs context However if ever your job has continue on error flag set to true and you check the job result via the needs context you'll get success while the job actually fails

**To Reproduce**
1. Create a failing jobs with continue-on-error set to true 
2. Create another job needing the first one and try to access the first job result

**Expected behavior**
Expected needs.job1.result to be failure even if flag continue-on-error is set to true

```
name: Test download Input
on:
  push:
      branches:    
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: "Check if artifact has already been built"
        id: dwnld
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.get-commit.outputs.commit }}_${{ matrix.apps }}
      - name: The job has failed
        if: ${{ failure() }}
        run: echo fails
  build_artifact:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo ${{ needs.job1.result }}
```
![Capture d’écran 2020-09-23 à 16 18 22](https://user-images.githubusercontent.com/24159274/94025096-6e073f80-fdb8-11ea-868e-0e0fec3f234b.png)

**Comment by crazy-matt** [comment]
Just to confirm that I've observed the same behaviour and implemented the status check myself based on an output usage.

**Comment by maxisam** [comment]
Any update on this issue? It has been a while.

**Comment by LDaneliukas** [comment]
@maxisam I just happened to stumble upon this as I've experienced the same issue. What did you mean that this is an edge case? I reproduced it with:

```
name: Test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.result == 'success'
    steps:
      - run: echo ${{needs.validate.result}}
```

Both jobs always run, because `job1` result is always seen as `success` even though it is failed and marked as such in the UI. 

Does not seem like an edge case 🤔
