### ISSUE TITLE
[cache] Executable exits with 126 after restoring on macOS

### ISSUE THREAD

**Issue by Cyberbeni** [actions/toolkit#619]
**Describe the bug**
I'm making an action that builds and caches tools written in Swift. When restoring a specific tool (SwiftLint, any version, not just a specific commit) on macOS and trying to run it, it exits with 126.
It works as expected with other tools and on Linux.

**To Reproduce**
Run this worfklow twice (first time it builds and caches, it will succeed, then second time it restores cache and will fail)
```yaml
name: "Bug test"

on: push

jobs:
  test:
    runs-on: macos-10.15
    steps:
    - name: Install SwiftLint
      uses: Cyberbeni/install-swift-tool@v2.1.8
      with:
        url: https://github.com/realm/SwiftLint
        version: '0.40.3'
    - name: Test tools in path
      run: |
        echo "class Test {}" > ./test.swift
        swiftlint lint ./test.swift
```
First run: https://github.com/Cyberbeni/install-swift-tool/runs/1335917683?check_suite_focus=true
Second run: https://github.com/Cyberbeni/install-swift-tool/runs/1335928476?check_suite_focus=true

**Expected behavior**
Executables work properly after caching and restoring them.
