### ISSUE TITLE
getInput does not replace envs

### ISSUE THREAD

**Issue by liudonghua123** [actions/toolkit#623]
**Describe the bug**
I use a github action (https://github.com/xresloader/upload-to-github-release) to upload some files which the name contains some environment variable, but it seems `getInput` does not process envs replacement.

```yaml
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${APP_NAME}-linux-.zip
          tags: true
          draft: false
```

https://github.com/xresloader/upload-to-github-release/blob/fdd72e02aaa9581a25515ebc2d8ec0492efb635a/src/index.ts#L15

**Expected behavior**
`getInput` can process envs or provide some options for envs replacement.
