### ISSUE TITLE
Runs Plugin: 'publish' - Undocumented Feature

### ISSUE THREAD

**Issue by warrenbuckley** [actions/toolkit#69]
The https://github.com/actions/upload-artifact repo `action.yml` contains the following:

https://github.com/actions/upload-artifact/blob/ec188c28d23c831d7283eb4280a4490eb5010092/action.yml#L11-L12

```yml
name: 'Upload artifact'
description: 'Publish files as workflow artifacts'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Directory containing files to upload'
    required: true
runs:
  plugin: 'publish'
```

So this leaves me to ask, what other things apart from running NodeJS & Docker Image/Container can we do as Action developers as mentioned in the documentation here - https://help.github.com/en/articles/metadata-syntax-for-github-actions#runs

/cc @chrispat & @damccorm
