### ISSUE TITLE
Incorrect context paths in conteiner

### ISSUE THREAD

**Issue by rosik** [actions/toolkit#708]
**Describe the bug**

The context is filled wrong when a job runs inside container:
- `${{ runner.temp }}`
- `${{ runner.tool_cache }}`
- `${{ github.action_path }}`

All these variables report a path without respect to the docker environment.

**To Reproduce**

Here is the repo with a reproducer: https://github.com/rosik/ga-test-public/ 

```
jobs:
  bug-in-container:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/repro # prints ${{ github.action_path }}

      - run: echo runner.temp = ${{ runner.temp }}
      - run: ls -al ${{ runner.temp }} || true

      - run: echo runner.tool_cache = ${{ runner.tool_cache }}
      - run: ls -al ${{ runner.tool_cache }} || true
```

**Actual output**

![image](https://user-images.githubusercontent.com/2205188/106929708-c0bd1480-6725-11eb-93e5-e8a36300191b.png)

**Expected behavior**

From logs, we can see the docker container is created as

```bash
 /usr/bin/docker create
 --name f5a8984beffb4a899f1f2715bfce01bf_centos7_c77d38
 --label 442333
 --workdir /__w/ga-test-public/ga-test-public
 --network github_network_7a20e69633be4acaaa53ae9145c97812 
 -e "HOME=/github/home"
 -e GITHUB_ACTIONS=true
 -e CI=true
 -v "/var/run/docker.sock":"/var/run/docker.sock"
 -v "/home/runner/work":"/__w"
 -v "/home/runner/runners/2.276.1/externals":"/__e":ro
 -v "/home/runner/work/_temp":"/__w/_temp"
 -v "/home/runner/work/_actions":"/__w/_actions"
 -v "/opt/hostedtoolcache":"/__t"
 -v "/home/runner/work/_temp/_github_home":"/github/home"
 -v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
 --entrypoint "tail" centos:7 "-f" "/dev/null"
```

So I expect variables to be:

- `runner.temp == "/__w/_temp"`
- `runner.tool_cache == "/__t"`
- `github.action_path == "/__w/ga-test-public/ga-test-public/./.github/actions/repro"`
