### ISSUE TITLE
Cache - excluding files or folders with ! not working

### ISSUE THREAD

**Issue by dhadka** [actions/toolkit#713]
**Describe the bug**

Excluding a file or folder does not work as expected with caching.  For example,

```
~/cache
!~/cache/subfolder
```

is matching:

```
../../../cache
```

I think this is because [caching uses `implicitDescendants: false`](https://github.com/actions/toolkit/blob/main/packages/cache/src/internal/cacheUtils.ts#L46).  Since we're not traversing any descendants, the negation pattern does not match anything.

One option is to just set `implicitDescendants: true`, but this may add inefficiencies as we will need to enumerate all the files and generate a large "includes file" for `tar`.  We essentially need it to scan the descendants but stop whenever the entire folder is included.  For example, the following files:

```
~/cache/foo.txt
~/cache/bar.txt
~/cache/src/main.c
~/cache/src/lib/baz.dll
~/cache/bin/main.exe
```

with the glob patterns of `~/cache` and `!~/cache/bin` should produce the list:

```
~/cache/foo.txt
~/cache/bar.txt
~/cache/src
```

**To Reproduce**

See https://github.com/dhadka/cache-test-exclusion

**Expected behavior**

Negated files / folders are excluded from the cache.

**Comment by mustaphazorgati** [comment]
Any updates here?

**Comment by lhotari** [comment]
There is a workaround. Excluding works if you have all patterns in the same "level", for example

```
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/pulsar
```

this is what we use in apache/pulsar, full example here:

https://github.com/apache/pulsar/blob/master/.github/workflows/ci-integration-process.yaml#L55-L65

**Comment by swarajpeppermint** [comment]
> There is a workaround. Excluding works if you have all patterns in the same "level", for example
> 
> ```
>           path: |
>             ~/.m2/repository/*/*/*
>             !~/.m2/repository/org/apache/pulsar
> ```
> 
> this is what we use in apache/pulsar, full example here:
> 
> https://github.com/apache/pulsar/blob/master/.github/workflows/ci-integration-process.yaml#L55-L65

Was trying to cache apt, using
```
path: |
    /var/cache/apt/archives/*
    !/var/cache/apt/archives/lock
    !/var/cache/apt/archives/partial
 ```
 But it still gives me a permission error for trying to access the partial folder:
 ` EACCES: permission denied, scandir '/var/cache/apt/archives/partial' `

**Comment by motss** [comment]
Thanks for the workaround in https://github.com/actions/toolkit/issues/713#issuecomment-850321461. It works like a charm. 

Here are my findings:

```yml
# 1. This will cache everything recursively inside `/a` excluding `/a/b`
path: |
    /a/*
    !/a/b

# 2. This will cache everything recursively inside `/a` including `/a/b`
path: |
    /a
    !/a/b

# 3. This will cache everything recursively inside `/a` including `/a/b`
#    with an unexpectedly huge total cache size (~6x, your mileage might vary)
#    and I don't see any visible differences when compared to 1. and 2.
path: |
    /a/**
    !/a/b

# Conclusion
# Just use 1. for the best of both worlds until the glob issue is fixed.
# Worth mentioning that modifying the value of `path` will affect the caches with the exact same `key`,
# so each cache is unique by its own `key` and `path`.
```
