### ISSUE TITLE
Context missing some values

### ISSUE THREAD

**Issue by krystof-k** [actions/toolkit#745]
**Describe the bug**

`context` object is missing some values in comparison with `${{ github }}`.

**To Reproduce**

Run:

```yaml
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
         with:
           script: |
             console.log('${{ github.head_ref }}');
             console.log(context.head_ref);
```

Result:

```
branch-name
undefined
```

**Expected behavior**

Value (the whole context object) is the same.
