### ISSUE TITLE
503 on chunk upload

### ISSUE THREAD

**Issue by RSickenberg** [actions/toolkit#765]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.  

If your issue is relevant to this repository, please include the information below:

**Describe the bug**
On cache post, I got a 503 error or unavailable keys for restoring.
I'm using it to save .npm caches and cypress install but it doesn't works.

**To Reproduce**
A. Run a job into a container, in my case: `container: cypress/browsers:node12.18.3-chrome89-ff86`
1. uses `cypress-io/github-action@v2` with a `github/cache@v2` before.
2. Wait until the end
3. Check output: `Warning: uploadChunk (start: 67108864, end: 100663295) failed: Cache service responded with 503`

**Expected behavior**
- The upload who would pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/16922548/114066549-22237000-989c-11eb-9349-1cbdaf0d8b5e.png)

**Desktop (please complete the following information):**
 - OS: Self-hosted runner: `Current runner version: '2.277.1'` on Ubuntu
 - Version: `@v2`

**Additional context**
```
2021-04-08T16:44:04.8306990Z ##[group]Run actions/cache@v2
2021-04-08T16:44:04.8307543Z with:
2021-04-08T16:44:04.8308036Z   path: ~/.cache/Cypress
build
node_modules

2021-04-08T16:44:04.8309737Z   key: Linux-node_modules-build-fc9e2ae169dbc48149296a3ad67254c72829aeb2c10852070989fa5e64e6b57b
2021-04-08T16:44:04.8311518Z   restore-keys: Linux-node_modules-build-

2021-04-08T16:44:04.8312106Z ##[endgroup]
2021-04-08T16:44:04.8318995Z ##[command]/usr/bin/docker exec  126bceacdfce55bb92d76e05069ef34770cfb40d8d40104790e52f0b8dba6cd3 sh -c "cat /etc/*release | grep ^ID"
2021-04-08T16:44:05.8125878Z Cache not found for input keys: Linux-node_modules-build-fc9e2ae169dbc48149296a3ad67254c72829aeb2c10852070989fa5e64e6b57b, Linux-node_modules-build-
```
```
2021-04-08T16:50:24.0259093Z [warning]uploadChunk (start: 67108864, end: 100663295) failed: Cache service responded with 503
```

**Comment by majg0** [comment]
Got the same symptom via `rush install --no-link` in our monorepo.

```yaml
jobs:
  install:
    runs-on: ubuntu-20.04
    name: install
    strategy:
      fail-fast: true
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        name: Load rush install cache
        with:
          path: |
            common/temp
            !common/temp/build-cache
            !common/temp/eslint
            !common/temp/ts-jest
          key: rush-install-${{ env.install-cache-version }}-node-${{ matrix.node }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml', 'libraries/*/package.json', 'subsystems/*/*/package.json') }}
          restore-keys: rush-install-${{ env.install-cache-version }}-node-${{ matrix.node }}-
      - name: setup-node
        uses: ./.github/actions/setup-node
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: ${{ matrix.node }}
      - name: rush install
        run: node common/scripts/install-run-rush.js install --no-link
        if: steps.cache.outputs.cache-hit != 'true'
```

Failing intermittently. Why?
