### ISSUE TITLE
support repeated workflow events

### ISSUE THREAD

**Issue by D-Nice** [actions/toolkit#81]
In the case of monorepos, I may wish to run a specific worklow for parts of a projects, only if a specific directory containing said project changes, as to not unnecessarily pollute action output when adding features of other projects, and avoid unnecessary cpu cycle consumption of the github actions service. This of course is possible atm, with something as simple as this:

```yaml
on:
  # trigger action if anything in this path changes
  push:
    paths: 
    - project3/src/*
```

However, I would still like to see everything tested, even if it was just other parts being changed, once it makes it into an important branch like master or develop, whilst still applying the above filter.

I would hope the following would work to achieve this, but it does not, and complains about push already having been declared:

```yaml
on:
  # trigger action if anything in this path changes
  push:
    paths: 
    - project3/src/*
  # trigger always on master and develop
  push:
    branches: 
    - master
    - develop
```

Doing the following, simply limits the workflow to running only if the said path changes in master/develop:
```yaml
on:
  # trigger action if anything in this path changes on master|develop
  push:
    paths: 
    - project3/src/*
    branches: 
    - master
    - develop
```
 as it should in that case, but I would like to see the above work, or if it already can please enlighten me :). For now I can just trigger on all branches, as that is preferable to limited triggering even on master|develop. Preferably the above more flexible event filtering would be ideal. I understand I can use pull_requests as well (but I don't consider it sufficient), and creating a duplicate identical workflow with just a slightly different event trigger is inelegant imo.
