### ISSUE TITLE
@actions/exec seems to ignore working-directory workflow setting

### ISSUE THREAD

**Issue by Firehed** [actions/toolkit#841]
**Describe the bug**
In an action configured with a [`working-directory`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun) setting, the default CWD of `exec.exec()` seems to ignore that setting.

**To Reproduce**
Create a workflow like this:
```yaml
name: "Docker: Build & Test"

on: [push] # irrelevant
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mydir # this bit
    steps:
      - uses: some/action
```
in a repository with some files in `mydir` at the root

And an action containing this:
```ts
import * as exec from '@actions/exec'
async function run(): Promise<void> {
  await exec.exec('pwd')
  await exec.exec('ls')
}
run()
```

**Expected behavior**
The `pwd` output should reflect the `working-directory` setting. The `ls` output should show the contents of that directory.

**Additional context**
Both the workflow-level and job-level `working-directory` setting are ignored. It's not clear how to get at that value to set it manually, if it's even possible.
