### ISSUE TITLE
Add `steps` variable?

### ISSUE THREAD

**Issue by mmkal** [actions/toolkit#863]
**Describe the enhancement**

It'd be nice to be able to get previous step outputs as part of the script.

**Code Snippet**

```yaml
- uses: actions/github-script@v4
  with:
    script: |-
      console.log('previous step value: ' + steps.some_previous_step.foo)
```

Alternatively could it be attached to `context`? so

```js
console.log('previous step value: ' + context.steps.some_previous_step.foo)
```

**Additional information**

Right now I think this has to be passed through via env vars or similar

```yaml
- uses: actions/github-script@v4
  with:
    script: |-
      console.log('previous step value: ' + process.env.FOO)
  env:
    FOO: ${{ steps.some_previous_step.foo }}
```

Which is ok, but it makes the script less portable and readable.
