### ISSUE TITLE
how to exclude an exit code in github actions workflow result status (failure)?

### ISSUE THREAD

**Issue by signorrayan** [actions/toolkit#908]
I have a workflow which in one of its steps, if the commands finish with exit code 1 (failure), i want to run next command/job (fix the problem which caused previous command failure), but i don't want that exit code 1 affect on a workflow result status.
in this situation, if i have exit code 1, even if i fix the problem, the result status will be failure, but i want if the second command fixed the problem, the result status be succeed.
is it possible?

here is my workflow.yml:

if the job build with command `run: black --check .` have exit code 1, i want to run job `reformat` to fix the problem and push that in repository. the second job works fine, but final result label is failure!!

```
name: autoblack
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Install Black
        run: pip3 install git+git://github.com/psf/black
        
      - name: Run black --check .
        run: black --check .
  
  reformat:
    runs-on: ubuntu-latest
    needs: [build]
    if: always() && (needs.build.result == 'failure')
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Install Black
        run: pip3 install git+git://github.com/psf/black
      - name: If needed, commit black changes to the pull request
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          black --fast .
          git config --global user.name 'autoblack'
          git config --global user.email 'signorrayan@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          echo "$NEEDS_CONTEXT"
          git commit -am "fixup: Format Python code with Black"
          git push
          echo "$NEEDS_CONTEXT"

```

**Comment by im-mortal** [comment]
GitHub uses the exit code of the last executed command to set the action's check run status.

To start with, there’s no need to run this workflow with two distinct runner jobs. One job (or even step) is quite enough for this. 
Secondly, you may want to disable the [default fail-fast behavior](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference) for your shell commands.
Then, you can use `black --check .` as a condition:

```sh
black --check . || black --fast .
…
git push
```

Having that said, this is an issue tracker for filing bugs. You may want to learn more about [shell scripts](https://github.com/techarkit/shell-scripting-tutorial), [GitHub Actions](https://docs.github.com/en/actions/learn-github-actions) and visit [GitHub Community](https://github.community/) is you have any questions left by then.

Good luck!

**Comment by signorrayan** [comment]
@im-mortal Thanks for the help. here is my new workflow. everything seems good, but the new problem is if a person create a Pull Request, this workflow will be failed because of the 'branch name'. for example  patch-1 (the branch that created pull request from that) >>  main (main branch in the main repository), will be fail, because the patch-1 branch does not exists in the main repository.

```
name: autoblack
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Black
        run: pip3 install git+git://github.com/psf/black
        
      - name: Run black --check .
        run: |
          black --check . || black --fast .
          git config --global user.name 'autoblack'
          git config --global user.email 'signorrayan@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push
```
