### ISSUE TITLE
More documentation is needed on how variables/secrets are rendered/scoped across reusable workflows & actions

### ISSUE THREAD

**Issue by bobleujr** [actions/toolkit#931]
Hi community, despite my love for Github Actions, I feel that reusable workflows need better documentation on how variables are available, scoped, rendered across reusable workflows, actions, etc. It's almost a shot in the dark trying to get our values running through workflows. 

# Example 1 - `${{ github.workspace }}`
In the workflow definition, `${{ github.workspace }}` renders to nothing, example
```
jobs:
  job_name:
    uses: .../.github/workflows/template.yaml@pipelines
    with:
      workspace: ${{ github.workspace }} # This resolves to empty string
```
However, in the reusable workflow `.../.github/workflows/template.yaml@pipelines`, it renders the correct path
```
on:
  workflow_call:
    inputs:
      someArg:
        description: 'Some args'
        required: true
        type: string

jobs:
  ci:
    name: Build, test and push
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.workspace }} # This prints something
```
Can't find where this is defined on the documentation

# Example 2 - Organization secrets

As stated here: https://github.com/actions/runner/issues/1413

Organization-level secrets aren't available in the caller workflow. But repo-specific repos are!

# Example 3 - env at root is not available at any moment in the caller workflow

In the caller workflow, if `env` is defined at the root level of the framework, values aren't achievable anywhere within the `jobs.<job_id>.with`. 

```
env:
   var1: 'value'

jobs:
  job_name:
    uses: .../.github/workflows/template.yaml@pipelines
    with:
      workspace: ${{ env.var1 }} # This doesn't work
      workspace: ${ var1 } # This doesn't work
```

Trying to access from the job definition is also invalid. * and doesn't allow for reuse of variables.
```
jobs:
  job_name:
    env: # This is invalid syntax
       var1: 'test' # This is invalid syntax
    uses: .../.github/workflows/template.yaml@pipelines
    with:
      workspace: ${{ github.workspace }} # This resolves to empty string
```

I mean, the list goes on. I have an entire document on how to rig solutions to get these values through, but I don't see it anywhere on the documentation. For instance, Azure DevOps has differences for `${{ var }}` `[ var ]` `$(var)` . 
![image](https://user-images.githubusercontent.com/6935646/139484096-ec9df8e3-0af3-44eb-aad3-4df39847ad12.png)
