### ISSUE TITLE
`Error: Parameter token or opts.auth is required` whenever trying to authenticate with GitHub

### ISSUE THREAD

**Issue by duncanmcclean** [actions/toolkit#938]
**Describe the bug**

I'm attempting to write my first GitHub action which needs access to Octokit to do some Github things. However, I've hit a blocker: I can't get past `Error: Parameter token or opts.auth is required`

I've looked at previous issues but they don't seem to help. I've tried passing in the GitHub token to my action in two ways:

```yaml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```yaml
with:
  myToken: ${{ secrets.GITHUB_TOKEN }}
```

But neither way seems to fix the issue and I'm not entirely sure what I'm doing wrong... I'd really appreciate any help.

**To Reproduce**

My action repo is public: https://github.com/duncanmcclean/post-release-comments

I'm using it like so in my test repo:

```yaml
- name: Comment on related issues
  uses: duncanmcclean/post-release-comments@v1.0.7
  with:
    version: ${{ github.ref }}
    changelog: ${{ steps.changelog.outputs.text }}
    myToken: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
For the error not to appear and for me to be able to authenticate with GitHub without any issues.

**Screenshots**

![image](https://user-images.githubusercontent.com/19637309/142734919-25e9a056-52b8-41dc-b980-928436bc199c.png)

**Additional context**

If it matters, my action is a public repo on an organisation and my test repo which I'm running the action on is a private repo on an organisation.
